package es.upm.fis2018.gm11_6.core;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : GM21 6
//  @ File Name : Conversacion.java
//  @ Date : 23/05/2018
//  @ Author :
//
//




public abstract class Conversacion {
	private String idConversacion;
	private Mensaje listaMensaje;
	
	
	
	// getters and setters
	public Mensaje getListaMensaje() {
		return listaMensaje;
	}
	public void setListaMensaje(Mensaje listaMensaje) {
		this.listaMensaje = listaMensaje;
	}
	public String getIdConversacion() {
		return idConversacion;
	}
	public void setIdConversacion(String idConversacion) {
		this.idConversacion = idConversacion;
	}
}
