package es.upm.fis2018.gm11_6.core;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : GM21 6
//  @ File Name : ConversacionGrupal.java
//  @ Date : 23/05/2018
//  @ Author :
//
//
public class  ConversacionGrupal {
	private String idConversacionGrupo;
	public ConversacionGrupal(){

	}
	
	public void mostrarMensajesGrupo() {
	
	}

	public void mostrarAlias() {

	}

	
	// GETTERS AND SETTERS
	public String getIdConversacionGrupo() {
		return idConversacionGrupo;
	}
	public void setIdConversacionGrupo(String idConversacionGrupo) {
		this.idConversacionGrupo = idConversacionGrupo;
	}	
}
